
#+STARTUP: showall

* Introduction

If you ever dreamed about creating and switching buffer groups at will
in emacs, [[https://github.com/chimay/torus][Torus]] is the tool you want.

Note that :

  - A buffer group is called a circle

  - The set of all buffer groups is called the torus (a circle of circles)

In short, this plugin let you organize your buffers by creating as
many buffer groups as you need, and quickly navigate between :

  - Buffers of the same group

  - Buffer groups (circles)


* History

This project is inspired by MTorus, which does not seem to be
maintained anymore.

See the repo at https://sourceforge.net/projects/mtorus.berlios/

I’ve a personal fork of it : https://github.com/chimay/mtorus

The code is complex, so I decided to write a new version from scratch,
easier to maintain and enjoying more recent features of emacs.


* Features

  - Remember files and positions

    + Auto update of position each time you change buffer or group

  - Persistence

    + Save torus to a file

    + Load a torus from a file

    + Switch torus easily : just load another torus file

    + Load a file and append to the existing torus

  - On demand loading of files : great for big projects


* Configuration

#+begin_src emacs-lisp

  (require 'torus)

  (torus/init)

  (setq torus/prefix-key (kbd "s-t"))

  (torus/install-default-bindings)

  (setq torus/dirname "~/.emacs.d/torus/")

#+end_src


* Warning

I try to be mindful when I code, but some bugs might remain, so be careful.
