
#+STARTUP: showall

#+TAGS: TOC(t)

* Table of contents                                                     :TOC_2_gh:
- [[#introduction][Introduction]]
  - [[#history][History]]
  - [[#goal][Goal]]
- [[#step-by-step][Step by Step]]
  - [[#first-circles][First Circles]]
  - [[#moving-around][Moving around]]
  - [[#square-the-circle][Square the Circle]]
  - [[#splits][Splits]]
- [[#key-bindings][Key Bindings]]
  - [[#levels][Levels]]
  - [[#list-of-bindings][List of bindings]]
  - [[#shortcuts][Shortcuts]]
- [[#configuration][Configuration]]
  - [[#use-package][Use-package]]
- [[#warning][Warning]]

* Introduction

If you ever dreamed about creating and switching buffer groups at will
in emacs, [[https://github.com/chimay/torus][Torus]] is the tool you want.

In short, this plugin let you organize your buffers by creating as
many buffer groups as you need, add the buffers you want to it and
quickly navigate between :

  - Buffers of the same group

  - Buffer groups (circles)

Note that :

  - A location is a pair (filename . position)

  - A buffer group, in fact a location group, is called a circle

  - The set of all buffer groups is called the torus (a circle of circles)


** History

This project is inspired by MTorus. You can find the original sources
on the links below :

  - The repository of Stefan Kamphausen, the orignal author, is
    available at https://www.skamphausen.de/cgi-bin/ska/mtorus

  - The rewrite by Sebastian Freundt is available on
    https://sourceforge.net/projects/mtorus.berlios/

  - I’ve a personal fork of the second one :
    https://github.com/chimay/mtorus, but I won’t maintain it anymore

The code I forked is complex, so I decided to write a new version from
scratch, easier to maintain and enjoying more recent features of
emacs.


** Goal

Torus helps you to organize your files in groups that you create
yourself, following your workflow. You only add the files you want,
where you want. For instance, if you have a "organize" group with
agenda & todo files, you can quickly alternate them, or display them
in two windows. Then, if you suddenly got an idea to tune emacs, you
switch to the "emacs" group with your favorites configuration files in
it. Same process, to cycle, alternate or display the files. Note that
the torus containing all these groups can be saved on a file and
loaded later. Over time, your groups will grow and adapt to your
style.


* Step by Step


** First Circles

Let’s say we have the files =Juice=, =Tea=, =Coffe=. The first thing
to do is to create a group (a circle) which will contain them. So, we
launch ~torus-add-circle~ and answer =Drinks= to the prompt. Then, we
go to =Juice= and use ~torus-add-location~ to add it to the circle.
Same process with =Tea= and =Coffee=. We now have a circle =Drink=
containing three files.

If your files are not already opened in buffers, just use
~torus-add-file~ to add them in the circle.

If you want to create another circle, let’s say =Fruits=, simply
launch ~torus-add-circle~ again, and enter another name. You can then
add the files =Apple=, =Pear= and =Orange= to it. You can even also
add =Juice=, a file can be added to more than one circle.

Now, suppose that in the =Juice= file, you have a Pineapple and a
Mango sections, and you want to compare them. Just go to the Pineapple
section, use ~torus-add-location~. It will add the location
(=Juice . pineapple-position=) to the current circle. Then, go to
the Mango section, and do the same. The (=Juice . mango-position=)
will also be added to the circle. You can then easily alternate both,
or display them in split windows.


** Moving around

You can cycle the files of a circle with ~torus-next-location~ and
~torus-previous-location~. You can also switch file with completion by using
~torus-switch-location~. It works well with Helm.

To cycle the circles, use ~torus-next-circle~ and
~torus-previous-circle~. To go to a given circle with completion, use
~torus-switch-circle~.


** Square the Circle

Over time, the number of circles will grow. Completion is great, but
if you just want to alternate the two last circles in history, you’ll
probably prefer ~ŧorus-alternate-circles~. You can also alternate two
last files inside the same circle with
~torus-alternate-in-same-circle~. So, you have the square :

| circle 1, file 1 | circle 1, file 2 |
| circle 2, file 3 | circle 2, file 4 |

at your fingertips.

Finally, ~torus-alternate~ alternate two last history files,
regardless of their circles.


** Splits

If you prefix a torus navigation function by C-u, the asked file will
be opened in a new window below. With C-u C-u, it will be in a new
window on the right.

If you want to see all the circle files in separate windows, use
~torus-layout-menu~ and chose between horizontal, vertical or grid
splits. You also have layouts with main window on left, right, top or
bottom side.

Your choice is remembered by torus for the current circle. You can
swith back to one window using the same layout function. The special
choice "manual" ask Torus not to interfere in your layout.

The maximum number of windows generated by the split functions
are conxtrolled by the vars ~torus-maximum-horizontal-split~ and
~torus-maximum-vertical-split~.


* Key Bindings

All bindings are available after the prefix key =<super-t>= by
default. You can see them by pressing <super-t><C-h>, or by installing
[[https://github.com/justbur/emacs-which-key][which-key]]. You can also define your own :

#+begin_src emacs-lisp
  (define-key torus-map (kbd "i") 'torus-info)
#+end_src


** Levels

The option ~torus-binding-level~, an integer between 0 and 3, decide
how many functions will be bound to keys : the higher it is, the more
bindings available. Level 1 or 2 is fine for most usages.

  - Level 0

    + Adding

    + Deleting

    + Moving around

    + Save and load

  - Level 1

    + History

    + Renaming

    + Moving and copying things

    + Join

    + Layout

  - Level 2

    + Reverse

    + Prefix

    + Autogroup

  - Level 3 : you surely don’t want to use these

    + Print main internal variables

    + Reset main internal variables

    + Miscellaneous


** List of bindings

Enter the prefix key, then :

  - =c= : create a new circle, add it to the torus

  - =l= : create the current location (file . position) to the current circle

  - =f= : add a file to the current circle ; more precisely, location (file . 1)

  - =i= : info about the current circle

  - =p= : print main variables content

  - =<down>= : next file (location) in circle

  - =<up>= : previous file in circle

  - ~=~ : switch file in circle

  - =<right>= : next circle

  - =<left>= : previous circle

  - =<space>= : switch circle

  - =s= : search file in all circles

  - =<PageDown>= : older file in file history

  - =<PageUp>= : newer file in file history

  - =^= : alternate last two visited files in history

  - =<= : alternate last two circles in history

  - =>= : alternate last two files in same circle in history

  - =h= : search in the file history

  - =n= : rename circle

  - =d= : delete file from circle

  - =D= : delete circle from torus

  - =w= : write torus to a file as Lisp code (with ".el" extension)

  - =r= : read torus from a torus file

  - =m= : move file in circle (not on disk)

  - =M= : move circle in torus

  - =C-m= : move file to another circle

  - =M-m= : move all files of the circle to another circle

  - =y= : copy, add the (file . position) to another circle

  - =j= : join the files of two circles, a new circle is created to
    contain them

  - =#= : layout menu

    + =m= : manual mode, leave unchanged

    + =o= : only one window, delete the others

    + =h= : split horizontally to display all files of the circles

    + =v= : split vertically to display all files of the circles

    + =g= : split in a grid to display all files of the circles

  - =! l= : reverse location order (file order) in a circle

  - =! c= : reverse circle order in the torus

  - =! d= : deep reverse : reverse both locations and circle

  - =:= : prefix circles names


*** Torus operations

You can create new toruses, beginning with a copy of the current
torus, and switch easily between them. A list of toruses, called Meta
Torus, is available. Some actions, like joining or autogrouping, also
create new toruses.

  - =+= : add a new torus to the torus list (variable ~torus-meta~)

  - =@= : switch torus

  - =N= : rename torus

  - =J= : join the circles of two toruses, a new torus is created to
    contain them

  - =g= : autogroup files in a new torus

    + =p= : group files by path

    + =d= : group files by directories

    + =e= : group files by extensions

  - =-= : delete a torus


** Shortcuts

I strongly suggest that you bind the functions you use most to quick
shortcuts. Here are some examples :

#+begin_src emacs-lisp
  (global-set-key (kbd "<S-s-insert>") 'torus-add-circle)
  (global-set-key (kbd "<s-insert>") 'torus-add-location)

  (global-set-key (kbd "<s-delete>") 'torus-delete-location)
  (global-set-key (kbd "<S-s-delete>") 'torus-delete-circle)

  (global-set-key (kbd "<C-prior>") 'torus-previous-location)
  (global-set-key (kbd "<C-next>") 'torus-next-location)

  (global-set-key (kbd "<C-home>") 'torus-previous-circle)
  (global-set-key (kbd "<C-end>") 'torus-next-circle)

  (global-set-key (kbd "s-SPC") 'torus-switch-circle)
  (global-set-key (kbd "s-=") 'torus-switch-location)
  (global-set-key (kbd "s-^") 'torus-switch-torus)

  (global-set-key (kbd "s-*") 'torus-search)
  (global-set-key (kbd "s-/") 'torus-search-history)

  (global-set-key (kbd "<S-prior>") 'torus-history-newer)
  (global-set-key (kbd "<S-next>") 'torus-history-older)

  (global-set-key (kbd "C-^") 'torus-alternate)

  (global-set-key (kbd "<S-home>") 'torus-alternate-circles)
  (global-set-key (kbd "<S-end>") 'torus-alternate-in-same-circle)
#+end_src


* Configuration

Here is a sample configuration :

#+begin_src emacs-lisp

  (require 'torus)

  (setq torus-prefix-key "s-t")

  ;; Range 0 -> 3
  ;; The bigger it is, the more bindings.
  (setq torus-binding-level 1)

  ;; Created if non existent
  (setq torus-dirname "~/.emacs.d/torus/")

  ;; Set it to t if you want autoload of torus on Emacs startup
  (setq torus-load-on-startup t)

  ;; Set it to t if you want autosave of torus on Emacs exit
  (setq torus-save-on-exit t)

  ;; Where to auto load & save torus
  (setq torus-autoread-file "~/.emacs.d/torus/last.el")
  (setq torus-autowrite-file torus-autoread-file)

  (setq torus-history-maximum-elements 30)

  (setq torus-maximum-horizontal-split 3)
  (setq torus-maximum-vertical-split 4)

  (torus-init)

  (torus-install-default-bindings)

#+end_src


** Use-package

If you declare Torus with ~use-package~ and want the start/quit hooks
to load/save your torus file, you’ll have to add a ~:hook~ section to
the declaration :

#+begin_src emacs-lisp
  (use-package torus
    :bind-keymap ("s-t" . torus-map)
    :bind (("<S-s-insert>" . torus-add-circle)
	   ("<s-insert>" . torus-add-location)
	   ("<s-delete>" . torus-delete-location)
	   ("<S-s-delete>" . torus-delete-circle)
	   ("<C-prior>" . torus-previous-location)
	   ("<C-next>" . torus-next-location)
	   ("<C-home>" . torus-previous-circle)
	   ("<C-end>" . torus-next-circle)
	   ("<S-prior>" . torus-history-newer)
	   ("<S-next>" . torus-history-older)
	   ("C-^" . torus-alternate)
	   ("<S-home>" . torus-alternate-circles)
	   ("<S-end>" . torus-alternate-in-same-circle)
	   ("s-SPC" . torus-switch-circle)
	   ("s-=" . torus-switch-location)
	   ("s-^" . torus-switch-torus)
	   ("s-*" . torus-search)
	   ("s-/" . torus-search-history)
	   :map torus-map
	   ("t" . torus-copy-to-circle))
    :hook ((emacs-startup . torus-start)
	   (kill-emacs . torus-quit))
    :custom ((torus-prefix-key "s-t")
	     (torus-binding-level 3)
	     (torus-verbosity 1)
	     (torus-dirname "~/.emacs.d/torus")
	     (torus-load-on-startup t)
	     (torus-save-on-exit t)
	     (torus-autoread-file "~/.emacs.d/torus/dernier")
	     (torus-autowrite-file torus-autoread-file)
	     (torus-history-maximum-elements 30)
	     (torus-maximum-horizontal-split 3)
	     (torus-maximum-vertical-split 4)
	     (torus-prefix-separator " : ")
	     (torus-join-separator " - "))
    :init (torus-init)
    :config (torus-install-default-bindings))
#+end_src

* Warning

Despite abundant testing, some bugs might remain, so be careful.
