
#+STARTUP: showall

* Introduction

If you ever dreamed about creating and switching buffer groups at will
in emacs, [[https://github.com/chimay/torus][Torus]] is the tool you want.

In short, this plugin let you organize your buffers by creating as
many buffer groups as you need, and quickly navigate between :

  - Buffers of the same group

  - Buffer groups (circles)

Note that :

  - A location is a pair (filename . position)

  - A buffer group, in fact a location group, is called a circle

  - The set of all buffer groups is called the torus (a circle of circles)


* History

This project is inspired by MTorus. You can find the original sources
on the links below :

  - The repository of Stefan Kamphausen, the orignal author, is
    available at https://www.skamphausen.de/cgi-bin/ska/mtorus

  - The rewrite by Sebastian Freundt is available on
    https://sourceforge.net/projects/mtorus.berlios/

  - I’ve a personal fork of the second one :
    https://github.com/chimay/mtorus, but I won’t maintain it anymore

The code I forked is complex, so I decided to write a new version from
scratch, easier to maintain and enjoying more recent features of
emacs.


* Features

  - Switch to next / previous group or buffer

  - Go to group or buffer with completion

    + It is recommended to install some good completion in the
      minibuffer (like [[https://github.com/emacs-helm/helm][helm]], [[https://github.com/abo-abo/swiper][swiper]] or ido)

  - Search among all files in the torus

  - History of buffers available

    + Navigate to newer / older in history

    + Alternate last two buffers

    + Alternate last two circles

    + Alternate last two buffers in same circle

  - Splits : available for most buffer related operations

    + Open buffer in a horizontal split (below) with prefix argument C-u

    + Open buffer in a vertical split (right) with prefix argument C-u C-u

    + Open all buffers of the same group in horizontal or vertical split

  - Remembers files and positions

    + Auto update of position each time you change buffer or group

    + Possibility to define multiple positions in the same file

    + Possibility do have the same file as member of distinct groups

  - Persistence

    + Save torus to a file (with buffer and input history)

    + Load torus from a file

    + On demand loading of files : great for big projects

    + Load a file and append to the existing torus

      * Possibility to add prefixes to the group names, to avoid confusion

  - Switch torus easily

    + Just load another torus file

    + Al list of loaded toruses is available

  - And more

    + Rename, move, copy, delete things


* Configuration

Here is a sample configuration :

#+begin_src emacs-lisp

  (require 'torus)

  (setq torus-prefix-key (kbd "s-t"))

  ;; Created if non existent
  (setq torus-dirname "~/.emacs.d/torus/")

  ;; Increase it if you want more and more functions available in bindings
  (setq torus-optional-bindings 0)

  (setq torus-save-on-exit t)

  (setq torus-history-maximum-elements 30)

  (setq torus-maximum-horizontal-split 3)
  (setq torus-maximum-vertical-split 3)

  (torus-init)

  (torus-install-default-bindings)

#+end_src


** Key bindings

All default bindings are available after the prefix key <super-t> by
default. You can see them by pressing <super-t><C-h>, or by installing
[[https://github.com/justbur/emacs-which-key][which-key]]. You can also define your own :

#+begin_src emacs-lisp
  (define-key torus-map (kbd "i") 'torus-info)
#+end_src

I suggest you add some quick bindings for the most used commands, for
instance :

#+begin_src emacs-lisp

  (global-set-key (kbd "<S-s-insert>") 'torus-add-circle)
  (global-set-key (kbd "<s-insert>") 'torus-add-location)

  (global-set-key (kbd "<s-delete>") 'torus-delete-location)
  (global-set-key (kbd "<S-s-delete>") 'torus-delete-circle)

  (global-set-key (kbd "<C-prior>") 'torus-previous-location)
  (global-set-key (kbd "<C-next>") 'torus-next-location)

  (global-set-key (kbd "<C-home>") 'torus-previous-circle)
  (global-set-key (kbd "<C-end>") 'torus-next-circle)

  (global-set-key (kbd "<S-prior>") 'torus-previous-history)
  (global-set-key (kbd "<S-next>") 'torus-next-history)

  (global-set-key (kbd "s-SPC") 'torus-switch-circle)
  (global-set-key (kbd "s-=") 'torus-switch-location)
  (global-set-key (kbd "s-^") 'torus-switch-torus)

  (global-set-key (kbd "s-/") 'torus-search)

  (global-set-key (kbd "C-^") 'torus-alternate)

#+end_src


* Warning

Despite abundant testing, some bugs might remain, so be careful.
